# Generated by Django 6.1.1 on 2026-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_estimated_minutes_module_max_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
