# Generated by Django 6.1.1 on 2026-10-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'module')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_passed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleschedule',
            name='custom_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moduleschedule',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SIX_MONTHLY', 'Every 6 Months'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], default='ANNUAL', max_length=20),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed',
        ),
    ]
